version: '3.8'

services:
  mysql_cont:
    image: mysql
    container_name: mysql_cont
    environment:
      - MYSQL_ROOT_PASSWORD=senna1
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=senna2
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api_container
    environment:
        - spring.datasource.url=jdbc:mysql://mysql_cont:3306/mysql
        - spring.datasource.username=root
        - spring.datasource.password=senna1
        - spring.jpa.hibernate.ddl-auto=update
        - spring.jpa.show-sql=true
        - spring.jpa.properties.hibernate.format_sql=true
        - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql_cont
    networks:
      - app_network
    ports:
      - "8080:8080"
    entrypoint: ["/app/wait-for-it.sh", "mysql_cont:3306", "--timeout=90", "--", "java", "-jar", "/app/app.jar"]

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
